apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-app
spec:
  replicas: 10
  selector:
    app: firstpod
  template:
    metadata:
      labels:
        app: firstpod
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8081
