name: Deploy Selenium Hub

on:
  push:
    branches:
      - main

jobs:
  deploy_selenium_hub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        minikube start --driver=docker
        minikube addons enable ingress
        minikube addons enable ingress-dns
        minikube status

    - name: Configure kubectl
      run: kubectl config use-context minikube

    - name: Deploy Selenium Hub
      run: kubectl apply -f selenium-hub-deployment.yaml
    
    - name: Deploy Selenium Hub Service
      run: kubectl apply -f selenium-hub-svc.yaml
    
    - name: Deploy Selenium Chrome Node
      run: kubectl apply -f selenium-node-chrome-deployment.yaml
    
    - name: Deploy Selenium Firefox Node
      run: kubectl apply -f selenium-node-firefox-deployment.yaml

