name: Deploy Selenium Hub

on:
  push:
    branches:
      - main

jobs:
  deploy_selenium_hub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Minikube
      run: |
        minikube start --driver=docker
        minikube addons enable ingress
        minikube addons enable ingress-dns
        minikube status

    - name: Configure kubectl
      run: kubectl config use-context minikube

    - name: Deploy Selenium Hub
      run: kubectl apply -f selenium-hub-deployment.yaml
    
    - name: Deploy Selenium Hub Service
      run: kubectl apply -f selenium-hub-svc.yaml
    
    - name: Deploy Selenium Chrome Node
      run: kubectl apply -f selenium-node-chrome-deployment.yaml
    
    - name: Deploy Selenium Firefox Node
      run: kubectl apply -f selenium-node-firefox-deployment.yaml
    - name: Get pods
      run: |
        kubectl get pods
        kubectl get service selenium-hub

    - name: Wait for Selenium Hub pod to be Running
      run: kubectl wait --for=condition=Ready pod -l app=selenium-hub --timeout=300s

    - name: Selenium HUB url
      run: |
        minikube service selenium-hub –-url >> temp.txt
        echo "Test Dinesh"
        selenium_hub_urls=$(cat temp.txt | awk '/port2\/4442/ {print $(NF)}' | tr -d '|[:space:]')
        echo "$selenium_hub_urls"
        echo "selenium_hub_urls=$url" >> selenium.properties
        echo "selenium_hub_urls=$url" >> $GITHUB_ENV
  run_tests:
      needs: deploy_selenium_hub
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        - name: Set up Selenium Hub URL
          run: |
            cat selenium.properties
          
        - name: Run Tests
          run: mvn clean test
